### ISSUE TITLE
Unhandled packet method packet.lookahead

### ISSUE THREAD

**Issue by wyklq** [vmware/p4c-xdp#103]
I tried to port P4C tutorial program - "calc" to XDP. The compiling failed with following error:
`p4c-xdp --Werror --target xdp -o calc.c calc.p4;`
terminate called after throwing an instance of 'Util::CompilerBug'
what(): In file: /home/wyklq/p4c/extensions/p4c-xdp/p4c/backends/ebpf/ebpfParser.cpp:294
Compiler Bug: calc.p4(114): Unhandled packet method packet.lookahead;
transition select(packet.lookahead<p4calc_t>().p,

The P4 source code is (".txt" is added to support github upload):
[calc.p4.txt](https://github.com/vmware/p4c-xdp/files/2587655/calc.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is indeed a bug, the compiler does not (yet) support the lookahead method.

**Comment by mbudiu-vmw** [comment]
I will try to do it tomorrow, if it's not too complicated.

**Comment by mbudiu-vmw** [comment]
There you go: https://github.com/p4lang/p4c/pull/1602
I haven't tested this thoroughly, though.

**Comment by mbudiu-vmw** [comment]
I will close this; please reopen if it still does not work.
