### ISSUE TITLE
Unexpected behavior when running xdp3.o

### ISSUE THREAD

**Issue by kwjjyn** [vmware/p4c-xdp#107]
Hi,  I'm testing the xdp3.p4 which parse L2, L3 and action could be drop or pass.
The table is described like this:
```P4
table dstmactable {
        key = { hdr.ethernet.destination : exact; }
        actions = {
            Fallback_action;
            Drop_action;
        }
        default_action = Drop_action;
        implementation = hash_table(64);
    }
```
After loading xdp3, I found that all the packets were passed to the kernel. 
My understanding is that if the default action of a table is Drop_action, Then if a table has no entries or the packet does not match the table entries, The default action will be executed on the packet. I didn't add any entries to the dstmactable table through a control plane program. So the packet should be the default action: they should be dropped . Is my understanding right? 
But the fact seems not like what I thought.

**Comment by kwjjyn** [comment]
Later I verified that the packet matching was actually executed in the order of the actions which defined in the table dstmactable. The first action in the dstmactable table is Fallback_action.So the packages passed. 

I want to ask what is the default_action used for? Did my previous understanding of default_action be wrong?

**Comment by williamtu** [comment]
It looks like a bug in our compiler
the generated xdp3.c code is below:
So it first lookup ingress_dstmactable, (in your case, it's empty)
then it looks up the Ingress_dstmactable_defaultAction, using key=0
So the first entry in this table will be executed.

```c
  value = BPF_MAP_LOOKUP_ELEM(Ingress_dstmactable, &key);
                if (value == NULL) {
                    /* miss; find default action */
                    hit = 0;
                    value = BPF_MAP_LOOKUP_ELEM(Ingress_dstmactable_defaultAction, &ebpf_zero);
                } else {
                    hit = 1;
                }
                if (value != NULL) {
                    /* run action */
                    switch (value->action) {
                        case Ingress_Fallback_action:
                        {
xoutdrop_0 = false;
                        }
                        break;
                        case Ingress_Drop_action:
                        {
xoutdrop_0 = true;
                        }
                        break;
```
@mbudiu-vmw  where do we process the 
default_action = Drop_action;?

**Comment by mbudiu-vmw** [comment]
The table contents should be setup by the control-plane, which should be executed at the beginning.
The control-plane is generated in the header file, in a function bracketed with `#if CONTROL_PLANE.`
The control-plane should install the Drop action into the Ingress_dstmactable_defaultAction table. Is it doing that?

**Comment by kwjjyn** [comment]
I didn't use control plane to populate the table.  In the generated code of xdp3.c:
```c
value = BPF_MAP_LOOKUP_ELEM(Ingress_dstmactable, &key);
                if (value == NULL) {
                    /* miss; find default action */
                    hit = 0;
                    value = BPF_MAP_LOOKUP_ELEM(Ingress_dstmactable_defaultAction, &ebpf_zero);
                } else {
                    hit = 1;
                }
                if (value != NULL) {
                    /* run action */
                    switch (value->action) {
                        case Ingress_Fallback_action:
                        {
xoutdrop_0 = false;
                        }
                        break;
                        case Ingress_Drop_action:
                        {
xoutdrop_0 = true;
                        }
                        break;
```
At first , I think both of the Ingress_dstmactable_defaultAction and the Ingress_dstmactable should be empty.  And first it looks up the Ingress_dstmactable and value should be NULL .  And then it looks up the Ingress_dstmactable_defaultAction .

I guess what you mean is that the Ingress_dstmactable_defaultAction actions are the same as the Ingress_dstmactable actions before I run the control-plane.  So even if it looks up the Ingress_dstmactable_defaultAction , the first action is still the Fallback_action ?  So the packets r not dropped.

I notice the code which defines the default table's action in init_tables() in xdp3.h :
```c
static void init_tables()
{
    u32 ebpf_zero = 0;
    {
        int tableFileDescriptor = BPF_OBJ_GET(MAP_PATH "/Ingress_dstmactable_defaultAction");
        if (tableFileDescriptor < 0) { fprintf(stderr, "map Ingress_dstmactable_defaultAction not loaded\n"); exit(1); }
        struct Ingress_dstmactable_value value = {
            .action = Ingress_Drop_action,
            .u = {.Ingress_Drop_action = {}},
        };
        int ok = BPF_USER_MAP_UPDATE_ELEM(tableFileDescriptor, &ebpf_zero, &value, BPF_ANY);
        if (ok != 0) { perror("Could not write in Ingress_dstmactable_defaultAction"); exit(1); }
    }
}
```
So if I want to run the P4 program correctly , I must run the control plane to redefine the default table by using the init_table() ？

**Comment by williamtu** [comment]
yes, that's right. The control plane should first populate the table using init_tables().
Are you able to get it running with correct result?

**Comment by kwjjyn** [comment]
Yes. After I run the control plane with init_tables() , everthing seems correct.
Thank you again for your help.
