### ISSUE TITLE
What is the difference between bpf_obj_get() in libbpf.h and BPF_OBJ_GET() in init_tables()

### ISSUE THREAD

**Issue by kwjjyn** [vmware/p4c-xdp#109]
I notice that there are both functions to get map descriptor and update in the control plane of user_xdp5.c and the header of xdp5.h .
In user_xdp5.c , it's 
```c
fd = bpf_obj_get(MAP_PATH TABLE);
[...]
ret = bpf_update_elem(fd, &key, &value, BPF_ANY);
```
In xdp5.h, it's
```c
int tableFileDescriptor = BPF_OBJ_GET(MAP_PATH "/Ingress_dstmactable_defaultAction");
[...]
int ok = BPF_USER_MAP_UPDATE_ELEM(tableFileDescriptor, &ebpf_zero, &value, BPF_ANY);
```
I know the lowercase function in user_xdp5.c actually is from libbpf.h which finally calls the syscall:
```c
return syscall(__NR_bpf, BPF_OBJ_GET, &attr, sizeof(attr));
# or
return syscall(__NR_bpf, BPF_MAP_UPDATE_ELEM, &attr, sizeof(attr));
```
But where is the captital function BPF_OBJ_GET() definition ?  Why use this function in xdp.h ? 
And I did some test that I use lowercase function bpf_obj_get() in xdp5.h to replace BPF_OBG_GET(). It seems work

After google it , I didn't find any source code in linux kernel matches this . And just know that BPF_OBJ_GET is a type of bpf_cmd in /linux/bpf.h

**Comment by mbudiu-vmw** [comment]
Here is some documentation for BPF_OBJ_GET.
https://ferrisellis.com/content/ebpf_syscall_and_maps/#bpf-obj-pin-and-bpf-obj-get
The Linux kernel keeps changing, I am not sure whether our programs work with the latest kernels and header files.

**Comment by williamtu** [comment]
I think the uppercase BPF_OBJ_GET is used to replaced by pre-processor to replace to different implementation. In the case of kernel, BPF_OBJ_GET = bpf_obj_get. When we're doing userspace
testing, it gets replaced to the userspace implementation.

The bpf interfaces used in this project now was copied long time ago from kernel.
Now the community is shifting to use libbpf 
https://github.com/libbpf/libbpf
This is a mirror of bpf-next linux tree's tools/lib/bpf directory

We should remove the p4c-xdp/lib/ and link to libbpf.so

**Comment by kwjjyn** [comment]
Thanks for the information.  :smile:
