### ISSUE TITLE
compiler support for range lookup

### ISSUE THREAD

**Issue by maharishib** [vmware/p4c-xdp#115]
Hi,
Could this compiler support range for looking up key(just like bmv2)?

**Comment by mbudiu-vmw** [comment]
We do not support ternary lookups either. Range lookups could be converted to ternary lookups. Bpf has no range maps as far as I know.

**Comment by maharishib** [comment]
Is there a way to iterate over each entry in the BPF map. With that, I think I can solve my problem.

**Comment by mbudiu-vmw** [comment]
You can iterate in user space,  but not in the kernel.

**Comment by maharishib** [comment]
Okay, thanks.

**Comment by maharishib** [comment]
Is there any other way to implement range matching, as i want to use the priority of rules also.

**Comment by mbudiu-vmw** [comment]
If you can give an example of how you would do it in raw ebpf perhaps we can implement it in the compiler.

**Comment by maharishib** [comment]
Suppose we have to match 3 columns, match data is (V1, V2, V3).
Now, For the first case, consider the table data as below. I want, rule 1 to be matched. (X is don't care, that is I don't care what value is placed there).
-------------------------------------------------------
|column A | column B | column C| priority| => Action
------------------------------------------------------
|      V1      |      V2      |      V3      |     0     | => ActionParam1
|      V1      |      V2      |       X       |     1     | => ActionParam2
------------------------------------------------------

Now, For the first case, consider the table data as below. I want, rule 2 to be matched. (X is don't care, that is i don't care what value is placed there).
-------------------------------------------------------
|column A | column B | column C| priority| => Action
------------------------------------------------------
|      V1      |      V2      |      V3      |     1     | => ActionParam1
|      V1      |      V2      |       X       |     0     | => ActionParam2
------------------------------------------------------
In bmv2, I implement this don't care condition using range(0->2^(length of the field)-1) and used priority to match the rules.

**Comment by maharishib** [comment]
In raw ebpf, I was thinking to iterate over the MAP using bpf_get_next_key. And then for each key, get the whole element if key matches the current packet data using lookup or any other method. Also while iterating, compare it with previously matched rules.

**Comment by mbudiu-vmw** [comment]
You cannot write loops in ebpf programs. Bounded loops are considered, but i don't think iteration over map entries will ever be supported. Anyway, if you want fast packet processing you don't have time for loops.

**Comment by maharishib** [comment]
Ok, Thanks
