### ISSUE TITLE
invalid indirect read from stack off

### ISSUE THREAD

**Issue by maharishib** [vmware/p4c-xdp#116]
Using bpf_map_update_elem(&ebpf_outTable, &ebpf_zero, &xout.output_port, BPF_ANY) in C file generated gives an error while offloading: invalid indirect read from stack off -268+0 size 4
After removing this line code is offloaded correctly

**Comment by mbudiu-vmw** [comment]
Can you supply the p4 program that leads to incorrect code being generated?

**Comment by maharishib** [comment]
The program is quite large, also I can not paste the code here due to some restrictions, Can you specify which parts of the program can lead to this error.

**Comment by maharishib** [comment]
Solved, the problem. I was not setting the default xout.output_port and xout.output_action.
