### ISSUE TITLE
p4x-xdp support for PSA

### ISSUE THREAD

**Issue by mestery** [vmware/p4c-xdp#132]
### Is your feature request related to a problem? Please describe.

Howdy! I'm curious if there has been any thought about supporting [P4 portable switch architecture](https://github.com/p4lang/p4-spec/tree/main/p4-16/psa) with the p4c-xdp compiler, and what that might look like. I've been playing around with the p4x-xdp compiler a bit, and it's really nice! PSA support would make it even better. :)

### Describe the solution you'd like

It would be ideal if it would be able to support the PSA P4 file similar to how the DPDK backend supports PSA (and also PNA): https://github.com/p4lang/p4c/tree/main/backends/dpdk

### Additional context

Opening this issue in case others who follow p4c-xdp are interested in something like this.

**Comment by mbudiu-vmw** [comment]
There isn't much work done on this project currently - one reason being that it's not clear that anyone is using it.
(I suspect no one really is, since no one complains about the bugs.)
Your proposal is in principle doable, but it would require a design about how the PSA pipeline is integrated with the Linux kernel pipeline - for example, what ebpf hook is used for the egress control.
If you have cycles to devote to this project I will be very happy to help with advice, code review, and implementation.
I personally don't know enough about the kernel datapath to embark on this project, and I am also using most of my available development cycles for supporting the p4c open-source compiler.

**Comment by mestery** [comment]
Thanks for the quick reply @mbudiu-vmw. It's unclear how much time I would have to devote to this project, but I'd like to at least dig a bit deeper. Can you give me some rough pointers on where I'd start for something like this? Thanks for any help!

**Comment by mbudiu-vmw** [comment]
I will point you to two presentations I gave about related subjects:
[Understanding the open-source P4-16 compiler](http://budiu.info/work/p4-compiler22.pptx)
P4 Developer Days, online meeting, February 15, 2022
[Comparing P4 and EBPF](http://budiu.info/work/p4+ebpf-21.pptx)
P4-ebpf task force, Virtual Presentation, January 21, 2021

This project would benefit mostly from the participation of someone who has used ebpf in the kernel for networking before and has a good understanding of the best way to do things of the sort.

There is a side issue that the way code is generated currently for ebpf is not very efficient, so if you want a high performance implementation I would consider doing a different design.

**Comment by mestery** [comment]
> I will point you to two presentations I gave about related subjects: [Understanding the open-source P4-16 compiler](http://budiu.info/work/p4-compiler22.pptx) P4 Developer Days, online meeting, February 15, 2022 [Comparing P4 and EBPF](http://budiu.info/work/p4+ebpf-21.pptx) P4-ebpf task force, Virtual Presentation, January 21, 2021
> 
I've read those, they are quite helpful. They focus on an area I am less familiar with (compiler technology). Which correlates to the next item.

> This project would benefit mostly from the participation of someone who has used ebpf in the kernel for networking before and has a good understanding of the best way to do things of the sort.
> 
I  am hoping that can be me! I've written a bunch of eBPF and XDP programs over the past two years, I hope I can help to map what we need to eBPF. I am thinking of putting together a diagram which shows the PSA objects and paths and how we can map them into eBPF and/or XDP. Do you think this is a good place to start?

> There is a side issue that the way code is generated currently for ebpf is not very efficient, so if you want a high performance implementation I would consider doing a different design.

Dually noted, and something we should probably file an issue for.

**Comment by rst0git** [comment]
@mestery Tomasz Osiński (@osinstom) will give a talk about a [PSA implementation](https://github.com/P4-Research/psabpf) for eBPF programs at the P4 Developer Days on March 1, 2022.

**Comment by mestery** [comment]
@rst0git Looks like this work is already well underway, thanks for sharing! @osinstom I look forward to hearing your talk!

**Comment by mbudiu-vmw** [comment]
Let's then continue this conversation after we listen to that talk. I am not familiar with their recent work either.

**Comment by mbudiu-vmw** [comment]
I will close this issue; conversation should be directed to https://github.com/p4lang/p4c/pull/3139.
