### ISSUE TITLE
XDP metadata support

### ISSUE THREAD

**Issue by thomascalvert-xlnx** [vmware/p4c-xdp#136]
### Is your feature request related to a problem? Please describe.

XDP has support for arbitrary metadata via the `xdp_md->data_meta` pointer - see for example the `bpf_xdp_adjust_meta()` call.

Current `p4include/xdp_model.p4` defines 2 metadata variables for the Control block only, `xdp_input` and `xdp_output`.

This doesn't fit very well with the XDP model:

* Metadata is expected to be available in the parser & deparser blocks too.
* Metadata is passed through unless explicitly changed. (Having separate variables means the program needs to explicitly copy input to output.)
* Metadata contents are user-defined.

### Describe the solution you'd like

Suggest that we have a user metadata variable which is available to all blocks. This would mimic the `user_meta` field in PSA.

Note that there is already a `user_metadata` field in ebpfParser, but it seems to be ignored in the p4c-xdp code.

In the kernel, metadata is prefixed to the packet data however we should be careful not to generalise this assumption, as other platforms may instead have metadata in some kind of sideband channel.

### Describe alternatives you've considered

It is important to differentiate between user metadata & system metadata. The existing xdp_in/out variables are clearly system metadata (which contain the input/output port numbers) and are defined by the target (kernel).

User metadata is by definition user-defined any may change format from one program to another. As far as the compiler is concerned it is simply an array of bytes accompanying the packet.

### Additional context

I'm not sure what has already been done here and would welcome any context. I have a prototype implementation of the above but would appreciate feedback before I go too far down this road. Thanks!

**Comment by mbudiu-vmw** [comment]
The p4c-ebpf backend of the p4c open-source project is actively developed. XDP target support has been added recently.
https://github.com/p4lang/p4c/pull/3752 I suspect that the p4c backend already does everything this backend does, so perhaps we should archive this project. Maybe you can see whether the other project is closer to your needs. It is better tested, that's for sure.
