### ISSUE TITLE
Failed to run the test cases due to bpf header missing on fresh Ubuntu16.04

### ISSUE THREAD

**Issue by JunhoSuh** [vmware/p4c-xdp#56]
Hi,

After building p4-xdp on Ubuntu16.04, I'd like to run all test cases to valid p4-xdp correctly working! However, do make under the tests directory, some error messages come out! plz see below~

In my guess, it seems can't find the proper bpf header, not in "/usr/include/linux/bpf.h". In the file, for example, there is no type BPF_PROG_TYPE_XDP in enum bpf_prog_type!

I installed linux-headers-4.10.0-28-generic and included it in Makefile under lib directory, but it conflicts with the existing headers!

========================
p4@p4-VirtualBox:~/workspace/p4c/extensions/p4c-xdp/tests$ uname -a
Linux p4-VirtualBox 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

p4@p4-VirtualBox:~/workspace/p4c/extensions/p4c-xdp/tests$ make
make -C ../lib/
make[1]: Entering directory '/home/p4/workspace/p4c/extensions/p4c-xdp/lib'
gcc -I -g -c bpf_load.c
In file included from bpf_load.c:25:0:
bpf_helpers.h:45:11: error: ‘BPF_FUNC_get_stackid’ undeclared here (not in a function)
  (void *) BPF_FUNC_get_stackid;
           ^
bpf_helpers.h:47:11: error: ‘BPF_FUNC_probe_write_user’ undeclared here (not in a function)
  (void *) BPF_FUNC_probe_write_user;
           ^
bpf_helpers.h:49:11: error: ‘BPF_FUNC_current_task_under_cgroup’ undeclared here (not in a function)
  (void *) BPF_FUNC_current_task_under_cgroup;
           ^
bpf_helpers.h:55:11: error: ‘BPF_FUNC_skb_get_tunnel_opt’ undeclared here (not in a function)
  (void *) BPF_FUNC_skb_get_tunnel_opt;
           ^
bpf_helpers.h:57:11: error: ‘BPF_FUNC_skb_set_tunnel_opt’ undeclared here (not in a function)
  (void *) BPF_FUNC_skb_set_tunnel_opt;
           ^
bpf_helpers.h:61:11: error: ‘BPF_FUNC_xdp_adjust_head’ undeclared here (not in a function)
  (void *) BPF_FUNC_xdp_adjust_head;
           ^
bpf_helpers.h:90:11: error: ‘BPF_FUNC_skb_load_bytes’ undeclared here (not in a function)
  (void *) BPF_FUNC_skb_load_bytes;
           ^
bpf_helpers.h:98:11: error: ‘BPF_FUNC_skb_under_cgroup’ undeclared here (not in a function)
  (void *) BPF_FUNC_skb_under_cgroup;
           ^
bpf_helpers.h:100:11: error: ‘BPF_FUNC_skb_change_head’ undeclared here (not in a function)
  (void *) BPF_FUNC_skb_change_head;
           ^
bpf_load.c: In function ‘load_and_attach’:
bpf_load.c:78:15: error: ‘BPF_PROG_TYPE_TRACEPOINT’ undeclared (first use in this function)
   prog_type = BPF_PROG_TYPE_TRACEPOINT;
               ^
bpf_load.c:78:15: note: each undeclared identifier is reported only once for each function it appears in
bpf_load.c:80:15: error: ‘BPF_PROG_TYPE_XDP’ undeclared (first use in this function)
   prog_type = BPF_PROG_TYPE_XDP;
               ^
bpf_load.c:82:15: error: ‘BPF_PROG_TYPE_PERF_EVENT’ undeclared (first use in this function)
   prog_type = BPF_PROG_TYPE_PERF_EVENT;
               ^
bpf_load.c:84:15: error: ‘BPF_PROG_TYPE_CGROUP_SKB’ undeclared (first use in this function)
   prog_type = BPF_PROG_TYPE_CGROUP_SKB;
               ^
bpf_load.c:86:15: error: ‘BPF_PROG_TYPE_CGROUP_SOCK’ undeclared (first use in this function)
   prog_type = BPF_PROG_TYPE_CGROUP_SOCK;
               ^
Makefile:9: recipe for target 'bpf_load.o' failed
make[1]: *** [bpf_load.o] Error 1
make[1]: Leaving directory '/home/p4/workspace/p4c/extensions/p4c-xdp/lib'
Makefile:17: recipe for target 'bpfloader' failed
make: *** [bpfloader] Error 2

**Comment by JunhoSuh** [comment]
I replaced bpf.h in /usr/include/linux with the file in /usr/src/linux-headers-4.10.0-28/include/uapi/linux by creating symbolic link, then finally I can compile and pass the all test cases!

**Comment by mbudiu-vmw** [comment]
You have to configure the linux kernel with support for ebpf, it is not on by default.
