### ISSUE TITLE
Const Entries Not Supported

### ISSUE THREAD

**Issue by Netroman** [vmware/p4c-xdp#57]
The following code causes a syntax error:
```
        const entries = { 
            (0) :  l2l3_lookup(0xAABBCCDDEEFF,0xFFEEDDCCBBAA,0xa0000001,0x0a000001);
        }  
```

From @mbudiu-vmw in #53 :
"There is no support for const entries yet. But please file issues for every one of these."

**Comment by mbudiu-vmw** [comment]
I have already filed an issue https://github.com/p4lang/p4c/issues/991 about this.
The xdp compiler is built on top of the ebpf compiler, so this issue belongs there.

**Comment by mbudiu-vmw** [comment]
This issue has been solved in the ebpf compiler.
