### ISSUE TITLE
Compiler error with unisgned integers

### ISSUE THREAD

**Issue by Anmol-007** [vmware/p4c-xdp#59]
Hello,
As we know, the compilation process involves two parts P4 -> P4c -> .c and .h and .c -> .o. In the /p4c-xdp/tests/ folder, we ran the make command which completes both the phases of compilation. 

When compiling with clang from the .c file to .o, the following error is encountered:

> In file included from xdp2.c:3:
./xdp2.h:16:5: error: unknown type name 'u32'
    u32 input_port; /* bit<32> */
    ^
./xdp2.h:21:5: error: unknown type name 'u32'
    u32 output_port; /* bit<32> */
    ^
.
.
.
./xdp2.h:44:5: error: unknown type name 'u8'
    u8 ebpf_valid;
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Makefile:55: recipe for target 'xdp2.o' failed
make: *** [xdp2.o] Error 1

The program terminates with these errors. Can someone please guide us regarding this issue?
Thank you for your time and help.
Sincerely,

**Comment by williamtu** [comment]
Hi,
Do you include bpf_helpers.h under /p4c-xdp/tests/ ?

**Comment by Anmol-007** [comment]
Hello William,
Thank you for responding. Yes, bpf_helpers is present in the /p4c-xdp/tests/ directory.


> root@compute5:~/workspace/XDP/p4c/extensions/p4c-xdp/tests# ls
Anmol_Readme   check-printk.txt  ipv6_routing_test.p4  load_and_verify.c  ndn_routing_test.p4  user_xdp10.c  xdp11.p4      xdp13.p4  xdp16.p4  xdp1-mod.p4  xdp3.p4  xdp6.p4  xdp9.p4
**bpf_helpers.h**  cscope.out        l2_switch_test.p4     Makefile           README.md            user_xdp5.c   xdp12.p4      xdp14.p4  xdp1.c    xdp1.p4      xdp4.p4  xdp7.p4  xdp.p4
bpfloader      ebpf_headers.p4   l3_routing_test.p4    Makefile_a         tags                 xdp10.p4      xdp13-mod.p4  xdp15.p4  xdp1.h    xdp2.p4      xdp5.p4  xdp8.p4

**Comment by mbudiu-vmw** [comment]
The types u8, u16, etc. are defined in this header.
You should figure out why you are getting these errors; there is probably some other header with the same name somewhere in the include path.

**Comment by williamtu** [comment]
Hi Anmol-007,
Do you still have the issue? if you include the bpf_helpers.h?

**Comment by Anmol-007** [comment]
Hi William,
   We reinstalled p4c-xdp and it worked. bpf_helpers.h was included before
as well but it wasn't working.

Thanks,
