### ISSUE TITLE
dword issue in .h file

### ISSUE THREAD

**Issue by Anmol-007** [vmware/p4c-xdp#60]
Hello,
When we compile the .p4 file using p4c-xdp, it generates a .h and .c file. The .h file is missing a macro for dword, which needs to be inserted manually. Can you please fix this?

Thank you,
Sincerely,

**Comment by williamtu** [comment]
can you post the dword macro you insert manually? Thanks!

**Comment by Anmol-007** [comment]
Hello William,

  This is the macro we added in the .h file.

> #define load_dword(data, b) __constant_ntohl(*(u64 *)((u8*)(data) + (b)))

Thank you,
Sincerely,

**Comment by williamtu** [comment]
thank you for reporting the issue. I pushed the change to the master.
