### ISSUE TITLE
Compiler support for p4 header stacks

### ISSUE THREAD

**Issue by zeeshanlakhani** [vmware/p4c-xdp#66]
Discussed this with @mbudiu-vmw over email, but this compiler should eventually support p4 [header stacks](https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html#sec-header-stacks). Adding this issue just to keep track of any work that is related.

**Comment by zeeshanlakhani** [comment]
@mbudiu-vmw since this builds atop the ebpf support in p4c, let me know if this should be opened there or can be left here.

**Comment by mbudiu-vmw** [comment]
Yes, this is an ebpf issue.

**Comment by zeeshanlakhani** [comment]
Will do.
