### ISSUE TITLE
Error: either "dev" is duplicate, or "xdp" is a garbage.

### ISSUE THREAD

**Issue by halidaltuner** [vmware/p4c-xdp#68]
Hello everyone,

We are working on P4C-XDP and XDP-BPF applications. But we have occured this error after XDP test scenario.

root@machine:~/p4c/p4c# ip link set dev ens1f0 xdp obj xdp16.o verb
Error: either "dev" is duplicate, or "xdp" is a garbage.

**Comment by williamtu** [comment]
Hi,
I guess your ip-link tool is too old.
can you try downloading the latest one?
see
https://github.com/vmware/p4c-xdp/blob/master/Dockerfile#L91

**Comment by halidaltuner** [comment]
Thank you William. I have solved this problem.
